name: buildapp
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Setup .NET Core SDK '6.0.x'
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore Curtains.Api/Curtains.Api.csproj
      - name: Build
        run: dotnet build --configuration Release --no-restore "Curtains.Api/Curtains.Api.csproj"
      - name: Test
        run: dotnet test --logger trx --results-directory "TestResults-6.0.x"