name: buildapp
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Setup .NET Core SDK '6.0.x'
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore Curtains/Curtains.Api/Curtains.Api.csproj
      - name: Build
        run: dotnet build --configuration Release --no-restore "Curtains/Curtains.Api/Curtains.Api.csproj"
      - name: Test
        run: dotnet test --logger trx --results-directory "TestResults-6.0.x" "Curtains/Curtains.Api/Curtains.Api.csproj"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results-6.0.x
          path: TestResults-6.0.x
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}