name: Create docker container

on:
  push:
    branches: [ "main", "develop", "initial-ci" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:

    - name: Check out the repo
      uses: actions/checkout@v3

    # - name: Log into registry
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.REGISTRY_USERNAME }}
    #     password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        # tags: ${{ secrets.REGISTRY_USERNAME }}/${{ image.name }}