name: .NET Core code analyze

on:
  push:
    branches: [ "master", "dev", "init_github_actions", "stage" ]
  pull_request:
    branches: [ "master", "dev", "init_github_actions", "stage" ]
  schedule:
    - cron: '21 2 * * 6'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ csharp ]
        dotnet-version: [ '6.0.x' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Install dependencies
      run: dotnet restore Curtains/Curtains.Api/Curtains.Api.csproj
      
    - name: Build
      run: dotnet build Curtains/Curtains.Api/Curtains.Api.csproj
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
